workflow:
  rules:
    - if: '$CI_COMMIT_TAG != null || $CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME == "develop"'
      when: always
    - when: never

default:
  tags:
    - docker

stages:
  - test
  - build
  - deploy

variables:
  STORAGE_DRIVER: vfs

Unit Test:
  image: python:3.6-alpine
  stage: test
  script:
    - pip install --upgrade pip
    - pip install -r wireguard-requirements.txt
    - python -m unittest discover image/scripts

Build image:
  image: registry.gitlab.com/pgalonza/basic-images/base-buildah:latest
  stage: build
  script:
    - dnf -y install buildah
    - buildah login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - chmod +x ./image/wireguard.sh
    - ./image/wireguard.sh
#    - buildah push $CI_REGISTRY_IMAGE $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - export IMAGE_TAG_NAME=$(if [[ $CI_COMMIT_REF_NAME == "master" ]] ;
      then echo 'latest'; elif [[ $CI_COMMIT_REF_NAME == "develop" ]] ;
      then echo develop; elif [[ $CI_COMMIT_TAG ]] ;
      then echo $CI_COMMIT_TAG; fi)
    - buildah push $CI_REGISTRY_IMAGE $CI_REGISTRY_IMAGE:$IMAGE_TAG_NAME

Deploy image:
  image: registry.gitlab.com/pgalonza/basic-images/base-ansible:latest
  stage: deploy
  needs:
    - Build image
  script:
    - dnf install -y python39 openssh-clients
    - pip3 install ansible
    - ansible-galaxy collection install containers.podman
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ansible-playbook ./deploy-wireguard.yml -i ./production.yml
  rules:
#    - if: '$CI_COMMIT_REF_NAME == "master"'
#      when: always
    - if: '$CI_COMMIT_REF_NAME == "develop"'
      when: manual
    - when: never
  environment: production
...
