image: centos:latest

default:
  tags:
    - docker

variables:
  STORAGE_DRIVER: vfs

Build image:
  stage: build
  script:
    - dnf -y install buildah podman
    - podman login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - chmod +x ./image/wireguard.sh
    - ./image/wireguard.sh
#    - buildah push $CI_REGISTRY_IMAGE $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - buildah push $CI_REGISTRY_IMAGE $CI_REGISTRY_IMAGE:latest

Deploy image:
  stage: deploy
  script:
    - dnf install -y python39 openssh-clients
    - pip3 install ansible
    - ansible-galaxy collection install containers.podman
    - ansible-playbook ./deploy-wireguard.yml -i ./production.yml -vvv

