image: centos:latest

default:
  tags:
    - docker

Build image:
  stage: build
  script:
    - dnf install buildah podman
    - podman login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - chmod +x ./images/wiregurad.sh
    - /images/wiregurad.sh
    - buildah push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - buildah push $CI_REGISTRY_IMAGE:latest
