---
- name: Install WireGuard
  hosts: vds
  become: yes
  vars:
    ug_id: 1050
  vars_files:
    - "{{ lookup('env', 'ANSIBLE_VARIABLES') }}"
  tasks:
    - name: Add wireguard to firewall service
      ansible.builtin.copy:
        src: ./files/wireguard.xml
        dest: /etc/firewalld/services/wireguard.xml
      notify:
        - reload_firewalld
        - enable_wireguard
    - name: Add WireGuard service user
      ansible.builtin.user:
        name: wireguard
        comment: WireGuard service user
        uid: "{{ ug_id }}"
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /home/wireguard/config
        state: directory
        mode: '0755'
        owner: wireguard
        group: wireguard
    - name: Install podman
      dnf:
        name: podman
        state: latest
    - name: Stop and Remove WireGuard container
      containers.podman.podman_container:
        name: wireguard
        state: absent
    - name: Pull a WireGuard latest image
      containers.podman.podman_image:
        name: registry.gitlab.com/pgalonza/wireguard-image
        tag: latest
    - name: Run WireGuard container
      containers.podman.podman_container:
        name: wireguard
        image: registry.gitlab.com/pgalonza/wireguard-image
        state: started
        privileged: yes
        volume:
          - /home/wireguard/config:/config
          - /lib/modules:/lib/modules
          - /usr/src/kernels:/usr/src/kernels
        env:
          PUID: "{{ ug_id }}"
          GUID: "{{ ug_id }}"
          SERVERURL: "{{ vpn_urls[groups['vds'].index(inventory_hostname)] }}"
          PEERS: "{{ peers_count }}"

  handlers:
    - name: Restart firewalld service
      command: firewall-cmd --reload
      listen: reload_firewalld
    - name: Enable wireguard service
      ansible.posix.firewalld:
        zone: public
        service: wireguard
        permanent: yes
        state: enabled
        immediate: yes
      listen: enable_wireguard
...
