---
- name: Install WireGuard
  hosts: vds
  become: yes
  vars:
    ug_id: 1050
    tag_name: develop
    network_mode: wireguard
  vars_files:
    - "{{ lookup('env', 'ANSIBLE_VARIABLES') }}"
  tasks:
    - name: Add wireguard to firewall service
      ansible.builtin.copy:
        src: ./files/wireguard.xml
        dest: /etc/firewalld/services/wireguard.xml
      notify:
        - reload_firewalld
        - enable_wireguard
    - name: Add WireGuard service user
      ansible.builtin.user:
        name: wireguard
        comment: WireGuard service user
        uid: "{{ ug_id }}"
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /home/wireguard/config
        state: directory
        mode: '0755'
        owner: wireguard
        group: wireguard
    - name: Install podman
      dnf:
        name: podman
        state: latest
    - name: Stop and Remove WireGuard container
      containers.podman.podman_container:
        name: wireguard
        state: absent
    - name: Remove an WireGuard image
      containers.podman.podman_image:
        name: "registry.gitlab.com/pgalonza/wireguard-image:{{ tag_name }}"
        state: absent
    - name: Adding container network
        containers.podman.podman_network:
          name: wireguard
          ipv6: yes
          subnet: 'fc00:bfb7:3bdb:ae34::/64'
    - name: Pull a WireGuard latest image
      containers.podman.podman_image:
        name: registry.gitlab.com/pgalonza/wireguard-image
        tag: "{{ tag_name }}"
    - name: Run WireGuard container
      containers.podman.podman_container:
        name: wireguard
        image: "registry.gitlab.com/pgalonza/wireguard-image:{{ tag_name }}"
        state: started
        sysctl:
          net.ipv4.conf.all.src_valid_mark: 1
        privileged: yes
        volume:
          - /home/wireguard/config:/config
          - /lib/modules:/lib/modules
          - /usr/src/kernels:/usr/src/kernels
        ports:
          - "51820:51820/udp"
        network: "{{ network_mode }}"
        env:
          PUID: "{{ ug_id }}"
          PGID: "{{ ug_id }}"
          SERVERURL: "{{ vpn_urls[groups['vds'].index(inventory_hostname)] }}"
          PEERS: "{{ peers_count }}"

  handlers:
    - name: Restart firewalld service
      command: firewall-cmd --reload
      listen: reload_firewalld
    - name: Enable wireguard service
      ansible.posix.firewalld:
        zone: public
        service: wireguard
        permanent: yes
        state: enabled
        immediate: yes
      listen: enable_wireguard
...
