---
vds:
  hosts:
    vds1:
      ansible_host: "{{ vds_ips[0] }}"
      ansible_user: "{{ ssh_user }}"
      ansible_port: "{{ ssh_custom_port }}"
#      ansible_ssh_private_key_file: "{{ lookup('env', 'SSH_KEY') }}"
...
