---
vds:
  hosts:
    vds1:
      ansible_host: "{{ vds1_ip }}"
      ansible_user: "{{ ssh_user }}"
      ansible_port: "{{ ssh_custom_port }}"
#      ansible_ssh_private_key_file: "{{ lookup('env', 'SSH_KEY') }}"
      vars:
        vpn_url: "{{ vpn1_url }}"
...
